### ISSUE TITLE
updated sweetjs-loader

### ISSUE THREAD

**Issue by jlongster** [petehunt/sweetjs-loader#5]
Hey Pete,

I rewrote this loader and updated it in a few ways. In particular, I added the ability to load readtables. Are you interested in continuing maintenance of this project? I can take over if not.

If you are, I can open a PR. https://github.com/jlongster/sweetjs-loader

**Comment by petehunt** [comment]
I am not interested in maintaining this if you are :)

I'll transfer the npm name to you and close this repo out. What's your npm username?

**Comment by jlongster** [comment]
Cool! npm username is jlongster

**Comment by petehunt** [comment]
OK, I have added you. When you're all done migrating it over feel free to remove me!

**Comment by conradz** [comment]
@jlongster would love to have your updated version published on npm (wanting to play with the new readtables support)! Also, issue tracking is not enabled on your repo (because it shows in Github as a fork of this repo).

**Comment by jlongster** [comment]
Done, just published! Thanks for reminding me. I will open the issue tracker.
